# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for Deno dependencies
  - package-ecosystem: "deno"
    directory: "/frontend/" # Adjust if your Deno files are in a subdirectory
    schedule:
      interval: "weekly"

  # Configuration for Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/ichor/" # Adjust if your Cargo.toml is in a subdirectory
    schedule:
      interval: "weekly"
