/**
 * gen-revision.ts — build-time cache revision map generator.
 *
 * Hashes every precached shell file with SHA-256 (crypto.subtle — no deps)
 * and emits `public/dist/cache-manifest.js`:
 *
 *   self.CACHE_MANIFEST = { buildId, files };
 *
 * `buildId` = SHA-256 over the sorted (path, hash) list, so any content
 * change to any shell file produces a new buildId → new cache name →
 * service-worker update. This replaces filename hashing, which the esbuild
 * build deliberately avoids.
 *
 * Run from frontend/: deno task gen-revision
 */

const SHELL_FILES = [
  "index.html",
  "manifest.webmanifest",
  "favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-512-maskable.png",
  "icons/apple-touch-icon.png",
  "sample.yaml",
  "dist/main.js",
  "dist/main.css",
  "dist/ichor.js",
  "dist/ichor_bg.wasm",
];

const pub = new URL("./public/", import.meta.url);

async function sha256(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    bytes as unknown as BufferSource,
  );
  return [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// URL→Windows-path conversion (Deno cannot read MSYS paths; .pathname
// yields /C:/... on Windows which stat rejects as absolute-rooted).
function toFsPath(url: URL): string {
  const m = url.pathname.match(/^\/([A-Za-z]:\/.*)/);
  return m?.[1] ?? url.pathname;
}

const files: Array<{ path: string; hash: string }> = [];
for (const rel of SHELL_FILES) {
  const bytes = await Deno.readFile(toFsPath(new URL(rel, pub)));
  const hash = await sha256(bytes);
  files.push({ path: rel, hash });
}

// buildId: hash of the whole manifest so one id covers every file.
const buildId = await sha256(
  new TextEncoder().encode(
    files.map((f) => `${f.path}:${f.hash}`).join("\n"),
  ),
);

const manifest = {
  buildId,
  files: files.map((f) => f.path),
};

const out = `// AUTO-GENERATED by gen-revision.ts — do not edit.\n` +
  `// Any shell change rewrites buildId, which renames the SW cache and\n` +
  `// forces a service-worker update (see public/sw.js).\n` +
  `self.CACHE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;

await Deno.writeTextFile(
  toFsPath(new URL("dist/cache-manifest.js", pub)),
  out,
);

console.log(
  `cache-manifest.js: buildId=${buildId.slice(0, 12)}… (${files.length} files)`,
);
