/**
 * WASM Bridge Module
 *
 * Provides TypeScript-friendly interfaces to the Rust WASM module.
 * Handles loading the WASM binary and wrapping Rust functions.
 *
 * Usage:
 *   const wasm = await initWasm();
 *   const graphJson = wasm.buildGraphFromYaml(yamlString);
 */

// Type definitions for the WASM module exports
interface WasmExports {
  parse_yaml: (yaml: string) => string;
  parse_yaml_to_json: (yaml: string) => string;
  node_count: (json: string) => number;
  root_names: (json: string) => string;
  build_graph_from_yaml: (yaml: string) => string;
  get_node_count: (yaml: string) => number;
  get_root_names: (yaml: string) => string;
  __wbindgen_malloc: (size: number, alignment: number) => number;
  __wbindgen_free: (ptr: number, size: number) => void;
}

// Cached WASM instance
let wasmPromise: Promise<WasmExports> | null = null;

/**
 * Initialize the WASM module.
 * Loads and instantiates the WASM binary on first call.
 * Subsequent calls return the cached promise.
 */
export async function initWasm(): Promise<WasmExports> {
  if (wasmPromise !== null) {
    return wasmPromise;
  }

  wasmPromise = (async () => {
    try {
      // Dynamic import of the WASM module generated by wasm-pack
      const wasmModule = await import("ichor");

      // Call the default export to load and instantiate the .wasm binary
      // Pass an object with module_or_path per the new wasm-pack init API
      await wasmModule.default({ module_or_path: "/ichor_bg.wasm" });

      // Extract the WASM exports we need
      const exports = wasmModule as unknown as WasmExports;
      return exports;
    } catch (error) {
      console.error("Failed to load WASM module:", error);
      throw new Error(
        "WASM initialization failed. Make sure you've run 'wasm-pack build --target web' in the /ichor directory.",
      );
    }
  })();

  return wasmPromise;
}

/**
 * Check if the WASM module has been initialized and is ready.
 */
export function isWasmReady(): boolean {
  return wasmPromise !== null;
}

/**
 * Parse a YAML string and return the result as a parsed JSON object.
 * This is a convenience wrapper that handles both parsing and deserialization.
 */
export async function parseYamlToJson(yaml: string): Promise<unknown> {
  const wasm = await initWasm();
  const jsonString = wasm.parse_yaml_to_json(yaml);
  return JSON.parse(jsonString);
}

/**
 * Build a graph from a YAML string and return the result as a parsed JSON object.
 */
export async function buildGraphFromYaml(yaml: string): Promise<unknown> {
  const wasm = await initWasm();
  const jsonString = wasm.build_graph_from_yaml(yaml);
  return JSON.parse(jsonString);
}

/**
 * Get the number of nodes in a YAML document.
 */
export async function getNodeCount(yaml: string): Promise<number> {
  const wasm = await initWasm();
  return wasm.get_node_count(yaml);
}

/**
 * Get the names of root nodes from a YAML document.
 */
export async function getRootNames(yaml: string): Promise<string[]> {
  const wasm = await initWasm();
  const jsonString = wasm.get_root_names(yaml);
  return JSON.parse(jsonString) as string[];
}

/**
 * Get the raw JSON string of a parsed YAML document.
 */
export async function getYamlJson(yaml: string): Promise<string> {
  const wasm = await initWasm();
  return wasm.parse_yaml_to_json(yaml);
}

/**
 * Get the raw JSON string of a built graph.
 */
export async function getGraphJson(yaml: string): Promise<string> {
  const wasm = await initWasm();
  return wasm.build_graph_from_yaml(yaml);
}
